### PR TITLE
General improvements & bug fixes

### PR DESCRIPTION
**Pull request by adams85**
I've given a bit of a face lift to this project:
* upgraded DllExport to the latest version
* switched to the new SDK-style project format
* fixed a bug related to assembly resolving (now the main plugin assembly can load its dependencies from the same directory)
* included basic logging of unhandled exceptions to aid diagnostics on plugin crash
* revised the native bindings (with special regard to string marshalling), did some minor perf improvements and corrected the broken imports
* implemented a proper TextWriter for host console logging

### CODE REVIEW

**Comment by mrexodia** [comment]
Looks awesome! I don’t have a lot of time to review in detail right now but I added you to the repo if you want to merge it :)

Btw this might be of interest for you: https://github.com/x64dbg/DotX64Dbg

**Comment by adams85** [comment]
Thanks for the invitation and for the hint about the other C# plugin project. I wasn't aware of it. It's a nice project and at first glance it makes this one pretty pointless. However, I've found that its bindings are still somewhat lacking (especially in the case of lower level APIs) and a bit heavy on dependencies (.NET Framework is usually included in Windows releases as opposed to .NET 5, which is not and C++/CLI also requires the vc runtime dlls of the compiler used to build the project.

So it's maybe not completely useless to maintain this more lightweight one. The nasty locked dlls on unloading issue, which slows down development, may be addressed using app domains. I plan to do some experiments regarding this and if I can make it work, I'll probably stick to this one.

BTW, I did this work apropos of creating a plugin which can trace calls and output the call tree in a nice structured format. I were making good progress but I ran into an issue. I'd like to ask for some pointers on this. Where can I contact you? Opening an issue in the main x64dbg repo ok to you?

**Comment by mrexodia** [comment]
@ZehMatt ping (not sure that works)

Yeah, I think it’s reasonable to have a simpler alternative (this plugin just outputs a DLL, Matt’s platform is more similar to IDAPython).

Feel free to contact me on the x64dbg Discord/Telegram or you can open an issue/discussion in the x64dbg repo :)

**Comment by ZehMatt** [comment]
> Thanks for the invitation and for the hint about the other C# plugin project. I wasn't aware of it. It's a nice project and at first glance it makes this one pretty pointless. However, I've found that its bindings are still somewhat lacking (especially in the case of lower level APIs) and a bit heavy on dependencies (.NET Framework is usually included in Windows releases as opposed to .NET 5, which is not and C++/CLI also requires the vc runtime dlls of the compiler used to build the project.)

Regarding .NET 5, I don't think its that big of a hassle to install and most computers probably have it installed because of other applications. Could you perhaps point out some of the bindings you are missing? I've focused primarily on things that people will use likely the most such as the assembler and disassembler, but if there is anything particular you are missing I won't mind adding it.

**Comment by adams85** [comment]
@ZehMatt I'm working on a tracing module where tons of callbacks happen, so I think it's advisable to use the lowest level APIs available to get the necessary info from x64dbg. AFAIK this would be the `DbgXXX` functions of the Bridge API. An example:

When I need to find out the destination of a call I can use the `DbgGetBranchDestination` function or I can evaluate the expression `dis.branchdest(addr)`. The latter obviously has some overhead compared to the former: instead of a direct function call, I need to build a string on my side, which then get parsed by the debugger. Although I didn't do perf tests, if the direct version is there I prefer to use that one.

BTW I had made an attempt to rewrite my plugin to use your native bindings but eventually I scrapped the idea because I didn't find good alternatives to the Bridge API functions. IIRC, I gave up when I was looking for an alternative to `DbgGetLabelAt` and I found `Symbols.Label.Get` but it couldn't make it work. Maybe this is just because of my limited understanding of the x64dbg APIs though since I'm still a noob at x64dbg and plugin writing. (On a side note, I noticed that one thing is off for sure: your bindings don't handle strings properly. x64dbg APIs uses UTF8-encoded strings everywhere [apart from the Titan engine] while you marshal them as simple ANSI strings.)

Anyway, your project is very promising, I'd definitely use it for scripting and for simpler plugins. I'm not a fan of reinventing the wheel at all... :D But as I mentioned I become aware of it after I had updated this one and (more or less) finished my tracer plugin. Now I probably wouldn't migrate it to your solution even if you exposed those low level APIs.

Maybe we can leave the status quo as is: your project is fine for those who want to consume the Script API primarily and this one could be a starter template who wants to dig deeper and/or tinker with the lower level APIs. What do you say?

**Comment by ZehMatt** [comment]
> @ZehMatt I'm working on a tracing module where tons of callbacks happen, so I think it's advisable to use the lowest level APIs available to get the necessary info from x64dbg. AFAIK this would be the `DbgXXX` functions of the Bridge API. An example:

A friend of mine wrote a dynamic instrumentation plugin, so I don't think there is a lack of functionality or performance. What you consider low level API on x64dbg is probably not accurate.

> When I need to find out the destination of a call I can use the `DbgGetBranchDestination` function or I can evaluate the expression `dis.branchdest(addr)`. The latter obviously has some overhead compared to the former: instead of a direct function call, I need to build a string on my side, which then get parsed by the debugger. Although I didn't do perf tests, if the direct version is there I prefer to use that one.

I can probably add a property to the Instruction something like ```TargetAddress```, right now you could simply check if the decoded instruction has ```IsControlFlow``` and read the first operand.

> BTW I had made an attempt to rewrite my plugin to use your native bindings but eventually I scrapped the idea because I didn't find good alternatives to the Bridge API functions. IIRC, I gave up when I was looking for an alternative to `DbgGetLabelAt` and I found `Symbols.Label.Get` but it couldn't make it work. 

Symbols.Label.Get should be working, do you remember what didn't work for you?

> Maybe this is just because of my limited understanding of the x64dbg APIs though since I'm still a noob at x64dbg and plugin writing. (On a side note, I noticed that one thing is off for sure: your bindings don't handle strings properly. x64dbg APIs uses UTF8-encoded strings everywhere [apart from the Titan engine] while you marshal them as simple ANSI strings.)

UTF8 should be fine as const char* as long I dont make assumptions about codepoints, right I'm just passing it along mostly. But that is definitely something I wanted to look into further.

> Anyway, your project is very promising, I'd definitely use it for scripting and for simpler plugins. I'm not a fan of reinventing the wheel at all... :D But as I mentioned I become aware of it after I had updated this one and (more or less) finished my tracer plugin. Now I probably wouldn't migrate it to your solution even if you exposed those low level APIs.
> 
> Maybe we can leave the status quo as is: your project is fine for those who want to consume the Script API primarily and this one could be a starter template who wants to dig deeper and/or tinker with the lower level APIs. What do you say?

As for the PR, its up to @mrexodia

**Comment by mrexodia** [comment]
Yeah I’m all good with merging this :) definitely doesn’t hurt to have. Was
just pointing out Matt’s plugin.

**Comment by adams85** [comment]
@ZehMatt

> What you consider low level API on x64dbg is probably not accurate.

That's possible as I'm still not super familiar with the x64dbg APIs. To me the Script and Bridge API seem to be roughly on the same abstraction level. TitanEngine is the lowest level I'm aware of. I'm only saying that I couldn't find an easy alternative of some Bridge functions in the Script API, thus, I ended up evaluating string expressions which is definitely one level higher than optimal in my case.

> Symbols.Label.Get should be working, do you remember what didn't work for you?

I'm not completely sure that it's a 1:1 alternative to `DbgGetLabelAt`. As far as I can remember, it returned `null` where `DbgGetLabelAt` just gave the expected answer. After I finish my ongoing work, I'll recheck this and let you know if there's some actual issue, not just some oversight by me.

> UTF8 should be fine as const char* as long I dont make assumptions about codepoints, right I'm just passing it along mostly. But that is definitely something I wanted to look into further.

`const char *` in itself is just an array of bytes, it can be interpreted in multiple ways. So it all depends on what encoding is used for marshaling.

As for P/Invoke, [it depends on the runtime/OS settings](https://docs.microsoft.com/en-us/dotnet/standard/native-interop/charset). I had to use the `CharSet.Ansi` + `UnmanagedType.LPUTF8Str` combination to make it work (or, in some cases, manual marshaling).

Unfortunately I can't tell how it's done in C++/CLI but there must be a way too.

**Comment by ZehMatt** [comment]
> > Symbols.Label.Get should be working, do you remember what didn't work for you?
> 
> I'm not completely sure that it's a 1:1 alternative to `DbgGetLabelAt`. As far as I can remember, it returned `null` where `DbgGetLabelAt` just gave the expected answer. After I finish my ongoing work, I'll recheck this and let you know if there's some actual issue, not just some oversight by me.

I'll have a look at it these days, last time I checked it was working as expected. Its something to add my in my local test plugin anyway.

> > UTF8 should be fine as const char* as long I dont make assumptions about codepoints, right I'm just passing it along mostly. But that is definitely something I wanted to look into further.
> 
> `const char *` in itself is just an array of bytes, it can be interpreted in multiple ways. So it all depends on what encoding is used for marshaling.
> 
> As for P/Invoke, [it depends on the runtime/OS settings](https://docs.microsoft.com/en-us/dotnet/standard/native-interop/charset). I had to use the `CharSet.Ansi` + `UnmanagedType.LPUTF8Str` combination to make it work (or, in some cases, manual marshaling).
> 
> Unfortunately I can't tell how it's done in C++/CLI but there must be a way too.

I fixed that stuff, its passing UTF8 now to the APIs and vice versa, I had that on my radar before but thanks for reminding me.

**Pull request merged**
